### ISSUE TITLE
RGB?

### ISSUE THREAD

**Issue by TerribleDev** [riezebosch/crayon#1]
Any plans to support RGB or hex values?

**Comment by silkfire** [comment]
@TerribleDev I was inspired to create a plugin that has support for both RGB and hex color values, as well as background colors.

See **[Pastel](https://github.com/silkfire/Pastel)** for more information.

**Comment by riezebosch** [comment]
@TerribleDev Sorry, I missed out on this one. Sure thing, nice idea!

@silkfire Nice one also!

**Comment by riezebosch** [comment]
Fixed: https://www.nuget.org/packages/Crayon/0.0.12. Thank you @silkfire!
