### ISSUE TITLE
NullReferenceException if string is null

### ISSUE THREAD

**Issue by chrfin** [riezebosch/crayon#24]
I observed a `NullReferenceException` when we tried to colorize a string which was `null`.  

This was tracked to the following code:

[https://github.com/riezebosch/crayon/blob/master/Crayon/StringExtensions.cs](https://github.com/riezebosch/crayon/blob/master/Crayon/StringExtensions.cs)

Maybe add a null-check there?

**Comment by riezebosch** [comment]
Solved by #31
