### ISSUE TITLE
Support for NO_COLOR

### ISSUE THREAD

**Issue by nikeee** [riezebosch/crayon#3]
I'd be happy if this library supported the `NO_COLOR` standard:
https://no-color.org

If this is not feasable, it would be nice to have a global switch to turn off coloring globally (this is also needed to turn off coloring when the program output is piped instead of printed).

**Comment by riezebosch** [comment]
Fixed: 2fae6fd81bab0e0f1c00986b6acedbe9a67d725e

**Comment by nikeee** [comment]
Thanks!
