### ISSUE TITLE
Crayon doesn't work

### ISSUE THREAD

**Issue by volkaris** [riezebosch/crayon#34]
Installed Crayon using NuGet in Rider,but can't use it,gets this error. Is there any fixes for this?

![Снимок экрана (97)](https://github.com/riezebosch/crayon/assets/110740644/4b892743-bc03-4a8e-a7cc-0399a8ffcd80)

**Comment by volkaris** [comment]
there is one phrase in Russian,it means could find selected file

**Comment by riezebosch** [comment]
the issue was automatically resolved?

**Comment by volkaris** [comment]
> the issue was automatically resolved?

Yes,There was a problem that I used static library instead of exe. If someone would have same problem just add OutputType Exe OutputType in you .csproj
